#!/usr/bin/env bash
# Generate .env for compose — stable secrets only.
# AWS credentials are NOT written here; litellm-proxy runs with network_mode: host
# and boto3 fetches them directly from IMDS at runtime (no expiry problem).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

# Preserve stable secrets across regenerations
POSTGRES_PASSWORD=""
LITELLM_MASTER_KEY=""
if [[ -f "${ENV_FILE}" ]]; then
    POSTGRES_PASSWORD=$(grep "^POSTGRES_PASSWORD=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2-)
    LITELLM_MASTER_KEY=$(grep "^LITELLM_MASTER_KEY=" "${ENV_FILE}" 2>/dev/null | cut -d= -f2-)
fi
[[ -z "${POSTGRES_PASSWORD}" ]] && POSTGRES_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
[[ -z "${LITELLM_MASTER_KEY}" ]] && LITELLM_MASTER_KEY="sk-$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"

VOLUMES="${VOLUMES:-${HOME}/Build/Volumes}"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by gen-env.sh — do not edit by hand
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
VOLUMES=${VOLUMES}
EOF

chmod 600 "${ENV_FILE}"
echo "[gen-env] .env written."
echo "[gen-env] LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}"
